### ISSUE TITLE
运行cta_fut_bt回测模块报类型错误

### ISSUE THREAD

**Issue by Shawn-Ecns** [wondertrader/wtpy#100]
报错信息：TypeError: datetime64 type does not support sum operations
<img width="517" alt="微信截图_20230406172736" src="https://user-images.githubusercontent.com/22656761/230335168-aabfb1f4-491a-4dcc-98e2-4ba61a05f30f.png">

**Comment by jack52518** [comment]
应该是因为 profit = df_closes.groupby(df_closes['day']).sum() 这句把closetime列也求和了，已经修改成只提出需要的列再求和，再试一下看看

**Comment by kk19990709** [comment]
2023年8月3日下载master分支，运行依然会遇到这个错误
