### ISSUE TITLE
特性请求：拉下来的文件 contracts.json里能不能增加合约到期日，保证金率等元信息

### ISSUE THREAD

**Issue by quant2008** [wondertrader/wtpy#104]
如题。

**Comment by wondertrader** [comment]
最新dev应该已经有了

**Comment by quant2008** [comment]
我刚才安装最新的dev，Version: 0.9.8。
然后我运行demo\ctp_loader\run.py，拉取期货合约，但是拉下来的contracts.json还是没有到期日等信息。举例如下
        "zn2403": {
            "name": "沪锌2403",
            "code": "zn2403",
            "exchg": "SHFE",
            "product": "zn",
            "maxlimitqty": 500,
            "maxmarketqty": 30,
            "minlimitqty": 1,
            "minmarketqty": 1
        },
