### ISSUE TITLE
WtWrapper的register_extended_data_loader调用异常

### ISSUE THREAD

**Issue by muxingtouzi** [wondertrader/wtpy#105]
按照下面方式给WtEngine添加 extended data loader 后会抛出异常

engine = WtEngine(eType = EngineType.ET_CTA, logCfg = 'logcfg.yaml')
engine.set_extended_data_loader(loader)

异常

AttributeError: 'WtWrapper' object has no attribute 'on_load_his_bars'
’
从代码来看 WtWrapper 没有 on_load_his_bars 方法

**Comment by wondertrader** [comment]
dev已修复
