### ISSUE TITLE
期权合约tick中合约代码不匹配的问题

### ISSUE THREAD

**Issue by yxqiango** [wondertrader/wtpy#114]
1. 合约代码更新后，czce期权合约格式为CZCE.TA2308.C6000。但是用该代码无法sub_ticks，tick中的合约代码仍然为CZCE.TA308.C6000。这导致下单时候用CZCE.TA2308.C6000，提示没有latest tick无法交易。该问题仅存在于czce交易所中，其他交易所目前可以正常交易。
2. 在on_calculator中get_tick函数同意无法读取到期权合约价格。
3. 0.9.7最新更新的stra_get_contract函数，无法用最新的合约代码读取到合约信息。而需要用交易所代码才能正常读取，例如CZCE.TA308C6000

**Comment by wondertrader** [comment]
这个问题，在wtpy最新的dev已经解决了，要么等0.9.8正式发布，要么你qq上直接联系我，我单独发给你
