### ISSUE TITLE
hft中 stra_get_comminfo 不适用期权合约

### ISSUE THREAD

**Issue by fffcc** [wondertrader/wtpy#115]
1. hft中 stra_get_comminfo 不适用期权合约，代码CZCE.MA.C.1950无法读取到结果
2. cta引擎中的stra_get_contracts 在hft中没有，希望也能添加一下。

**Comment by wondertrader** [comment]
这个我最近来完善一下

**Comment by wondertrader** [comment]
![image](https://github.com/wondertrader/wtpy/assets/62869597/1da96bd9-dfdc-441d-8489-e55c32a29bf4)
1、合约代码有统一标准
2、在dev分支都解决了，发布版本为0.9.8，请你关注一下
