### ISSUE TITLE
Hft模式输出的trades.csv缺少tag字段

### ISSUE THREAD

**Issue by JolyonWu** [wondertrader/wtpy#139]
Hft模式输出的trades.csv缺少tag字段，signals.csv 缺少usertag字段导致 web控制台读取持仓等信息的时候会报错
![19008954dcbd03b8aa52fa87ffd5a83d](https://github.com/wondertrader/wtpy/assets/34907351/61005e24-264d-4dce-b898-abf99a9ec881)

**Comment by wondertrader** [comment]
确认了一下，不是没输出，而是写到最后一列了，dev已修改，0.9.10会修正
