### ISSUE TITLE
demo中的datakit_fut正常运行无报错，但是接收不到数据

### ISSUE THREAD

**Issue by Weile-Chen** [wondertrader/wtpy#143]
可以成功运行 cta_fut_bt，运行demos/datakit_fut/runDT.py 连接simnow接收不到行情数据。

日志显示CTP连接登录成功，但是 storage/并没有rt数据，而且收盘后显示 "0 datas processed totally"
![1716988911999](https://github.com/wondertrader/wtpy/assets/13761928/a175e763-0a56-4f87-95c8-94a312175d13)

wtpy 0.9.9
python 3.9.19
系统 Ubuntu

**Comment by wondertrader** [comment]
是什么原因呢？
