### ISSUE TITLE
在ubuntu 18.04系统上运行出现中文乱码

### ISSUE THREAD

**Issue by qiuwei** [wondertrader/wtpy#4]
主要是因为依赖的wondertrader部分文件采用了GBK编码。
请等待wondertrader修改文件编码。

作为临时的解决方案，可以采用https://github.com/qiuwei/wtpy 的dev分支。

**Comment by wondertrader** [comment]
WonderTrader底层对接了不少交易接口，国内的交易接口很多都是GBK编码的，所以处理起来方便一些。加上WonderTrader一开始就是用MSVC来开发的，所以就一直沿用GBK编码了，这个问题可能比较难协调，我先关了issue，后面我再琢磨一下
