### ISSUE TITLE
WtDtHelper.py文件下的dump_ticks生成的csv没有exchg字段

### ISSUE THREAD

**Issue by dumengru** [wondertrader/wtpy#40]
查看了下应该是底层, WtDtHelper.cpp文件里缺了这个字段.
另外, 可以考虑将输出的小数位数作为参数暴露出来吗, 比如外汇品种小数位数大于3数据就不对了

**Comment by wondertrader** [comment]
最新dev已修复，小数位强制设置为6位，不能不设置，不然可能会变成科学计数法
