### ISSUE TITLE
回测速度怎么样？

### ISSUE THREAD

**Issue by nickhuangxinyu** [wondertrader/wtpy#6]
如果我要回测一个tick数据的策略，10年  2500天，每天28000个tick数据，这样的一次回测大概需要多久

**Comment by wondertrader** [comment]
> 每天28000

刚才做了一个粗略的测算，用我在公众号里的模型，分别用C++版本和Python版本回测，从20210104到20210118，一共11个交易日。C++版本耗时1.634s，Python版本耗时13.747s。换算成250个交易日，C++版本预计为37.136s，Python版本预计为312.432s。希望这个测算能对你有所帮助。
