### ISSUE TITLE
undefined symbol: _ZN3otp14HftStraBaseCtx11getOrderTagEj

### ISSUE THREAD

**Issue by swordkee** [wondertrader/wtpy#7]
ubuntu 20.04
$ ldd -r /usr/local/lib/python3.8/dist-packages/wtpy/wrapper/linux/libWtPorter.so
        linux-vdso.so.1 (0x00007ffff7c72000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4f61490000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4f6146d000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f4f61280000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4f61131000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4f61110000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4f60f10000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f4f616db000)
undefined symbol: _ZN3otp14HftStraBaseCtx11getOrderTagEj        (/usr/local/lib/python3.8/dist-packages/wtpy/wrapper/linux/libWtPorter.so)

$ c++filt _ZN3otp14HftStraBaseCtx11getOrderTagEj
otp::HftStraBaseCtx::getOrderTag(unsigned int)

**Comment by skyang2009** [comment]
我也有同样的问题

**Comment by skyang2009** [comment]
wtpy/wrapper/linux/ 里面的so动态库要用自己编译的才行，不能用git上面的版本，自己编译的so文件在在/root/wondertrader/src/build_Debug/bin/WtPorter

**Comment by wondertrader** [comment]
gcc里面对于inline的函数的处理和vs不大一样，这个wondertrader里做了修正，你可以用wondertrader里的代码自己编译一下看看

**Comment by wondertrader** [comment]
> wtpy/wrapper/linux/ 里面的so动态库要用自己编译的才行，不能用git上面的版本，自己编译的so文件在在/root/wondertrader/src/build_Debug/bin/WtPorter

好的，谢谢，那我先关掉问题了啊
