### ISSUE TITLE
HftContext.stra_cancel_all 出错

### ISSUE THREAD

**Issue by ZedRover** [wondertrader/wtpy#71]
Hftcontext.py 类的stra_cancel_all 中的WtWrapper.hft_cancel_all 因为 ret 中含有int 类型，无法在 python3
中使用bytes.decode(ret)

**Comment by wondertrader** [comment]
我看一下

**Comment by ZedRover** [comment]
<img width="699" alt="image" src="https://user-images.githubusercontent.com/29392414/186295883-6f50dab0-5a8b-4c38-834b-4bf2717e873b.png">
目前这么改是可以的

**Comment by wondertrader** [comment]
这个是回测框架还是实盘框架

**Comment by ZedRover** [comment]
hft 回测 我改的WtWrapper.py

**Comment by wondertrader** [comment]
> hft 回测 我改的WtWrapper.py

那问题是回测的还是实盘的？

**Comment by ZedRover** [comment]
回测的

**Comment by wondertrader** [comment]
这个问题不是你描述的那样，而是要对hft_cancel_all的返回值类型做一个声明，dev我改好发出来
