### ISSUE TITLE
ubuntu 20.04 CTP接口中文乱码的问题

### ISSUE THREAD

**Issue by skyang2009** [wondertrader/wtpy#8]
有没有好的解决办法
图中是在demos文件夹下面执行python3 runDt.py

![image](https://user-images.githubusercontent.com/696782/108618737-76dd6980-745b-11eb-8ce5-4db08ef231f2.png)

**Comment by wondertrader** [comment]
> 有没有好的解决办法
> 图中是在demos文件夹下面执行python3 runDt.py
> 
> ![image](https://user-images.githubusercontent.com/696782/108618737-76dd6980-745b-11eb-8ce5-4db08ef231f2.png)

有一个办法，就是把你控制台的编码改成gbk的，这个很难搞，要么全部翻译成英文，要不然就是你自己fork一套代码，全部改成utf8编码的。我这边处理的话，vs下编译会有问题。

**Comment by skyang2009** [comment]
CTP接口返回的数据也是GBK的，转码太麻烦了，所以代码还是全用gbk好了，我现在的经验是输出的日志内容尽量用英文就可以了

**Comment by wondertrader** [comment]
> CTP接口返回的数据也是GBK的，转码太麻烦了，所以代码还是全用gbk好了，我现在的经验是输出的日志内容尽量用英文就可以了

是的，我也发现了，也琢磨以后逐步改掉，不过进度没办法太快
