### ISSUE TITLE
期货夜盘K线合成问题

### ISSUE THREAD

**Issue by puddingsmall** [wondertrader/wtpy#81]
### **1.我的本地环境 0.9.5 0.9.4 0.9.3 三个版本都测试过期货夜盘24点前K线合成有问题**
![image](https://user-images.githubusercontent.com/59089657/207206221-892d3df6-7ce9-478b-9680-657f634cbecd.png)

### **2. windows服务器0.9.5版本测试过用行情记录器记录的历史数据合成的K线夜盘数据也有相同的问题**
![AT$C3~$GQQJ843~)7N~BOGG](https://user-images.githubusercontent.com/59089657/207202793-855bf88c-f785-40b4-be85-758177819543.png)
![4F5SB(BCWIO4)9{~VUZ67YR](https://user-images.githubusercontent.com/59089657/207202860-44e89178-65bd-420d-9ef2-12dfe718d7e7.png)
### **3. 我自己联系一位群友用他的数据和环境测试，夜盘输出k线也有问题**
![4J I$1T6$N}ODR(X}J{9R`I](https://user-images.githubusercontent.com/59089657/207202726-a1d68860-e037-425d-babf-1fa6193d59a5.jpg)

**Comment by wondertrader** [comment]
dev已修复，请更新到最新的dev
