### ISSUE TITLE
更新到最新的dev后，cta优化器报错

### ISSUE THREAD

**Issue by puddingsmall** [wondertrader/wtpy#82]
![image](https://user-images.githubusercontent.com/59089657/207752833-dd4d3ee8-0f41-4a56-bd4b-8869635fb353.png)
更新到最新的dev后，cta优化器报错
![image](https://user-images.githubusercontent.com/59089657/207753050-7c65edc7-47c2-4c97-b30d-67e023967fc4.png)

**Comment by wondertrader** [comment]
最新dev已解决
