### ISSUE TITLE
dev两个问题

### ISSUE THREAD

**Issue by puddingsmall** [wondertrader/wtpy#83]
1. [[mod]C++底层二进制文件更新到dev分支最新编译版本【截止到2022.12.13 22:16】](https://github.com/wondertrader/wtpy/commit/3bc68f1ad4eccc71dd6f0d4241707d3dcd5b9346)
回测K线能正常合成，但实盘时合成K线依然有问题
![image](https://user-images.githubusercontent.com/59089657/208027296-ef855ff1-7fbc-42ab-a865-c2777116769f.png)

2. [[mod]C++底层二进制文件更新到dev最新编译版本【截止到2022.12.15 17:15】](https://github.com/wondertrader/wtpy/commit/01bee8313e06e5f9c143d148f46999963c57a159)
更新后 cta_fut 初始化后会直接卡住
![$ E2X35WI7FV 1G7WPWGXJE](https://user-images.githubusercontent.com/59089657/208027379-052f3de7-89a6-40f8-8a9e-d6b42399ce96.png)

**Comment by wondertrader** [comment]
这两个问题，最新dev应该是解决了，我生产已经更新了，你现在还有重现吗

**Comment by puddingsmall** [comment]
wtpy=0.9.6.1
两个问题已经解决
![image](https://user-images.githubusercontent.com/59089657/225170451-daa9b9ab-67c0-4c1e-964e-724b9d16adf0.png)
