### ISSUE TITLE
希望datahelper增加ticks数据的导出

### ISSUE THREAD

**Issue by ZizhouJia** [wondertrader/wtpy#84]
赞wondertrader的工作，从专业程序员角度来看，非常棒！

QData数据源支持导出ticks数据，但datahelper还不支持导出ticks，希望增加ticks数据导出的接口

**Comment by wondertrader** [comment]
tick数据，我没买，没有做过，不确定数据要怎么清洗。要不然你改一个版本，提一个pr上来，我看下

**Comment by wondertrader** [comment]
wtpy不可能支持全部的三方数据源。如果你有这类需求，可以试用WtDataHelper的store_ticks接口来导出tick数据
