### ISSUE TITLE
ctp_loader 生成文件编码有问题

### ISSUE THREAD

**Issue by puddingsmall** [wondertrader/wtpy#86]
wtpy = 0.9.6.1
ctp_loader 生成的 contracts.json 和 commodities.json 文件编码有问题，导致cta_fut异常退出
![image](https://user-images.githubusercontent.com/59089657/210504186-6bdd6756-44b6-4ece-b271-dac430aaf7e2.png)

![image](https://user-images.githubusercontent.com/59089657/210504352-453bf36c-c0d2-4fda-97c4-cdf6188163fe.png)
强行加个 errors="ignore" 才能正常运行cta_fut

**Comment by zymmatt** [comment]
ctp_loader生成的新文件是gbk编码

**Comment by wondertrader** [comment]
这里确实有点问题，我还在想办法处理

**Comment by wondertrader** [comment]
最新dev已经改已经解决了，自动识别编码
