### ISSUE TITLE
订阅期货期权存在编码错误问题

### ISSUE THREAD

**Issue by zymmatt** [wondertrader/wtpy#87]
使用的是simnow通道，订阅期货期权后可以下单（如CFFEX.IO.IO2303-C-4100)，但是写入持仓时发现code变成了CFFEX.IO.2230，这导致on_order回调函数无法触发，持仓的查询也有问题，可能是行情转码发生了错误。

**Comment by wondertrader** [comment]
这个我正在修复

**Comment by wondertrader** [comment]
最新dev已经修复，我已经投入生产环境使用，目前一切正常
