### ISSUE TITLE
如何订阅主力合约

### ISSUE THREAD

**Issue by zymmatt** [wondertrader/wtpy#88]
比如说我的策略想跑几个月，这期间始终订阅某个期货品种的主力合约，而主力合约的代码会不断地变化，此时我应该如何订阅？形如 context.stra_get_bars(SHFE.rb.HOT)可以吗?

**Comment by wondertrader** [comment]
是这样的，直接使用SHFE.rb.HOT，但是要注意维护主力换月规则hots.json文件
