### ISSUE TITLE
Segmentation fault怎么调试

### ISSUE THREAD

**Issue by skyang2009** [wondertrader/wtpy#9]
root@iZ0jl3nc5j5s6c69yrpgreZ:~/wtpy-master/demos/datakit_fut# python3 runDT.py 
/usr/local/lib/python3.8/dist-packages/wtpy/wrapper/linux/libWtDtPorter.so
<CDLL '/usr/local/lib/python3.8/dist-packages/wtpy/wrapper/linux/libWtDtPorter.so', handle 2859ef0 at 0x7fdd2b1cdd30>
Segmentation fault

C++和Python混在一起太难搞了，不知道哪里配的不对

**Comment by wondertrader** [comment]
跨语言是很麻烦，你可以尝试用python -m pdb runDT.py来调试，如果还有问题，请到wondertrader下面发一个issue，我来看看

**Comment by skyang2009** [comment]
系统可以跑了，我是在mac下面写码然后同步到Ubuntu的服务器上编译和调试，经验一是Python用到的动态库尽量重新编译一下，二是所有代码和配置文件都要保存成gbk格式的。

![image](https://user-images.githubusercontent.com/696782/108809499-eb431480-75e3-11eb-9e89-c5300380b656.png)

**Comment by wondertrader** [comment]
> 系统可以跑了，我是在mac下面写码然后同步到Ubuntu的服务器上编译和调试，经验一是Python用到的动态库尽量重新编译一下，二是所有代码和配置文件都要保存成gbk格式的。
> 
> ![image](https://user-images.githubusercontent.com/696782/108809499-eb431480-75e3-11eb-9e89-c5300380b656.png)

你是在什么操作系统？

**Comment by skyang2009** [comment]
18.04LTS

**Comment by wondertrader** [comment]
> 18.04LTS

好的，已经解决就好了，这个问题后面会逐步完善的。issue我先关了
