### ISSUE TITLE
wtpy hft 一些问题

### ISSUE THREAD

**Issue by puddingsmall** [wondertrader/wtpy#90]
wtpy = 0.9.6.1

1. stra_buy 和 stra_sell  userTag必填参数, 不填会引发异常
![image](https://user-images.githubusercontent.com/59089657/217167008-c38f2c1d-2470-492f-a8fb-589b8dd3d564.png)

2.  ontrade和onorder 参数 userTag 回调为空值

4. 订阅主力合约时无法正常报单
![image](https://user-images.githubusercontent.com/59089657/217167279-41977325-43bf-4239-87a2-1dfa988342c4.png)

**Comment by wondertrader** [comment]
1/3好解决，2是是回测还是实盘？

**Comment by wondertrader** [comment]
2没复现，最新版请等0.9.7

**Comment by puddingsmall** [comment]
wtpy = 0.9.6.1 
我挂的simnow，昨晚测试了一下
![image](https://user-images.githubusercontent.com/59089657/225171212-0b7e1729-f839-44a0-8c74-d4115706fd96.png)
![image](https://user-images.githubusercontent.com/59089657/225171271-d95dfbe2-bfd8-4971-a767-b49422924d16.png)
![image](https://user-images.githubusercontent.com/59089657/225171546-051268fc-32e1-48af-b561-c2dc48c28414.png)
