### ISSUE TITLE
订阅期权合约遇到无法触发回调的问题

### ISSUE THREAD

**Issue by zymmatt** [wondertrader/wtpy#92]
0.9.6 dev 分支
订阅 SHFE.ru2306P13500， testUDP监听到了行情
在cta和hft引擎里订阅SHFE.ru.ru2306P13500 都无法触发on tick 或者 on bar, INE的期权合约也不行
但是CFFEX的期权合约可以触发on bar，无法触发 on tick

**Comment by wondertrader** [comment]
最新的dev应该已经修复

**Comment by zymmatt** [comment]
用最新的dev测试后发现on tick的触发还是不行
