### ISSUE TITLE
SEL引擎的绩效分析->累计净值数据为空

### ISSUE THREAD

**Issue by RickyLoveFreedom** [wondertrader/wtpy#94]
用wtpy测试sel_fut_bt示例时发现，sel引擎的累计净值一直为1，
![image](https://user-images.githubusercontent.com/21985820/219694769-2900c86a-e22e-4aae-809e-d0ed02906667.png)

而cta策略是可以获取到累计净值数据的。粗略跟踪了下CtaStraBaseCtx.cpp代码，发现是回测生成的funds.csv文件数据全部为0，
![image](https://user-images.githubusercontent.com/21985820/219695075-763aebb3-6389-4667-af77-cfa6b26ad972.png)
继续跟踪代码，发现读取资金数据  策略名.json的文件时，获取不到 fund的数据导致的，r如下图所示。
![image](https://user-images.githubusercontent.com/21985820/219695612-8baa5817-8cbc-41a2-be1a-9d3d12404803.png)
至于fund数据是怎么来的，c++水平有限就看不太懂了

**Comment by wondertrader** [comment]
这个应该已经解决了，请使用最新dev测试
