### ISSUE TITLE
请问在交易接口中，怎么获取所有order的信息

### ISSUE THREAD

**Issue by wutttao** [wondertrader/wtpy#97]
就期货来说，目前有持仓、持仓价，但是没有挂单的查询接口，看不到那些事已成交order，哪些事未成交的order

**Comment by wondertrader** [comment]
你好，WonderTrader的CTAEngine是不包含执行逻辑的，WonderTrader采用M+1+N的执行架构，M个策略在1个组合中，可以同时在N个交易通道交易，所以CTAStrategy是不能直接拿到交易通道的订单信息了。欢迎你深入了解WonderTrader的执行架构，这是专门针对很多大机构的需求，也可以用于多账户交易的场景

**Comment by wutttao** [comment]
我已经收到啦！http://shop108536602.taobao.com/shop/view_shop.htm?spm=a1z0e.1.10010.4.jV1nnz&v=1
